// Kernel Loader - Generic GPU kernel loading and caching infrastructure
//
// Provides unified interface for loading GPU kernels from:
//   - Embedded strings (build-time compiled)
//   - Source files (runtime compiled)
//   - Binary blobs (pre-compiled .metallib, PTX, SPIR-V)
//
// Supports kernel variants keyed by (name, dtype, size) tuples.

#ifndef KINET_GPU_KERNEL_LOADER_H
#define KINET_GPU_KERNEL_LOADER_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// =============================================================================
// Kernel Types
// =============================================================================

typedef enum {
    KINET_KERNEL_SOURCE_EMBEDDED = 0,  // Embedded as string constant
    KINET_KERNEL_SOURCE_FILE = 1,      // Load from file path
    KINET_KERNEL_SOURCE_BINARY = 2,    // Pre-compiled binary blob
} KinetKernelSourceType;

typedef enum {
    KINET_KERNEL_LANG_METAL = 0,
    KINET_KERNEL_LANG_CUDA = 1,
    KINET_KERNEL_LANG_PTX = 2,
    KINET_KERNEL_LANG_WGSL = 3,
    KINET_KERNEL_LANG_SPIRV = 4,
} KinetKernelLanguage;

// Kernel variant key for caching
typedef struct {
    const char* name;       // Kernel function name
    uint32_t dtype;         // Data type (KinetDtype)
    uint32_t size_hint;     // Size variant (0 = default)
    uint32_t flags;         // Additional flags
} KinetKernelVariant;

// Kernel source descriptor
typedef struct {
    KinetKernelSourceType type;
    KinetKernelLanguage lang;
    const char* source;         // Source string or file path
    size_t source_len;          // Length (0 = null-terminated)
    const void* binary;         // Binary data (for BINARY type)
    size_t binary_len;
    const char* entry_point;    // Entry function name
    const char* compile_opts;   // Compiler options (nullable)
} KinetKernelSource;

// Opaque kernel handle
typedef struct KinetKernel KinetKernel;

// Kernel cache (opaque)
typedef struct KinetKernelCache KinetKernelCache;

// =============================================================================
// Kernel Registry (embedded kernels)
// =============================================================================

// Embedded kernel entry (generated at build time)
typedef struct {
    const char* name;           // Kernel family name (e.g., "binary_add")
    const char* entry_point;    // Entry function name
    KinetKernelLanguage lang;
    const char* source;         // Embedded source string
    size_t source_len;
    const void* binary;         // Pre-compiled binary (nullable)
    size_t binary_len;
} KinetEmbeddedKernel;

// Registry of all embedded kernels (generated by CMake)
typedef struct {
    const char* backend;            // "metal", "cuda", "webgpu"
    const KinetEmbeddedKernel* kernels;
    size_t count;
} KinetKernelRegistry;

// Get embedded kernel registry for backend
const KinetKernelRegistry* kinet_kernel_registry_get(const char* backend);

// Find kernel by name in registry
const KinetEmbeddedKernel* kinet_kernel_registry_find(
    const KinetKernelRegistry* registry,
    const char* name
);

// =============================================================================
// Kernel Cache API
// =============================================================================

// Create kernel cache
KinetKernelCache* kinet_kernel_cache_create(void);

// Destroy kernel cache
void kinet_kernel_cache_destroy(KinetKernelCache* cache);

// Get cached kernel by variant
KinetKernel* kinet_kernel_cache_get(
    KinetKernelCache* cache,
    const KinetKernelVariant* variant
);

// Store kernel in cache
void kinet_kernel_cache_put(
    KinetKernelCache* cache,
    const KinetKernelVariant* variant,
    KinetKernel* kernel
);

// Clear all cached kernels
void kinet_kernel_cache_clear(KinetKernelCache* cache);

// Get cache statistics
void kinet_kernel_cache_stats(
    KinetKernelCache* cache,
    size_t* count,
    size_t* memory_bytes
);

// =============================================================================
// Kernel Loader API (backend-specific implementations)
// =============================================================================

// Compile kernel from source
KinetKernel* kinet_kernel_compile(
    void* device_context,   // Backend-specific device
    const KinetKernelSource* source
);

// Load kernel from binary
KinetKernel* kinet_kernel_load_binary(
    void* device_context,
    const void* binary,
    size_t binary_len,
    const char* entry_point
);

// Destroy kernel
void kinet_kernel_destroy(KinetKernel* kernel);

// Get kernel entry point name
const char* kinet_kernel_entry_point(KinetKernel* kernel);

// =============================================================================
// Utility Macros for Embedded Kernels
// =============================================================================

// Declare embedded kernel (used in generated headers)
#define KINET_DECLARE_KERNEL(name, lang) \
    extern const char kinet_kernel_##name##_source[]; \
    extern const size_t kinet_kernel_##name##_source_len;

// Define embedded kernel source
#define KINET_DEFINE_KERNEL(name, source_str) \
    const char kinet_kernel_##name##_source[] = source_str; \
    const size_t kinet_kernel_##name##_source_len = sizeof(kinet_kernel_##name##_source) - 1;

// Kernel registry entry
#define KINET_KERNEL_ENTRY(name, entry, lang) \
    { #name, entry, lang, kinet_kernel_##name##_source, kinet_kernel_##name##_source_len, NULL, 0 }

// Binary kernel registry entry
#define KINET_KERNEL_ENTRY_BINARY(name, entry, lang, bin, bin_len) \
    { #name, entry, lang, NULL, 0, bin, bin_len }

#ifdef __cplusplus
}
#endif

#endif // KINET_GPU_KERNEL_LOADER_H
